### ISSUE TITLE
Plot different comparison methods and sources in ps.py

### ISSUE THREAD

**Issue by bcipolli** [bcipolli/lateralized-components#27]
From @atsuch: Add R-, L-, and RL-concat to wb comparison overlaid on top of each other in `ps.py`

**Comment by atsuch** [comment]
@bcipolli, I'm trying to implement this in ps.py, but there is something I don't understand in your code. You track the sparsity of images in lines['above_001'], ['above_005'] and ['above_0005'], but these are not incorporated in the plot, are they? Am I missing something?

**Comment by bcipolli** [comment]
They are plotted here, right? 
https://github.com/bcipolli/lateralized-components/blob/c53f0891e222037c300ceaac975eecc26457d2b5/ps.py#L54

**Comment by atsuch** [comment]
Yeah I had trouble understanding that line. So np.asarray(lines.values()) is simply the array version of the dict, but [-1] select only the last element of that array, which are values of lines['err'], no? So I thought you are just plotting normalized lines['err'] here.

**Comment by bcipolli** [comment]
Ah see, you understood it well! Better than me haha.
`dict` is unordered, so I'm really not sure what the [-1] is doing there. In addition, the legend is commented out. So it looks like I merged some code I was playing around with.

I would remove the [-1] and add back the legend!

**Comment by atsuch** [comment]
OK, yeah, that's why I was confused...since dict is unordered, it's just by chance we were getting lines['err'] values. So it's actually supposed to show sparsity at different levels in addition to the similarity score. Got it!

**Comment by bcipolli** [comment]
You are :+1: :+1: :+1:

**Comment by bcipolli** [comment]
I think we're all set here; I'm closing as fixed by @atsuch .
